version: '3.8'
services:
  db:
    restart: always
    image: postgres
    container_name: auth_db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=auth_service"
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: unless-stopped
    container_name: cookie_redis
    ports:
      - "6379:6379"