-- +goose Up
-- SQL in this section is executed when the migration is applied.
CREATE TABLE IF NOT EXISTS public.users
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login          varchar(255) not null,
    password_hash varchar(255) not null,
    created_at    timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role            varchar(255) not null
);

CREATE TABLE IF NOT EXISTS public.users_have_roles
(
    user_id int REFERENCES public.users (id),
    role_id int REFERENCES public.roles (id)
);

CREATE TABLE IF NOT EXISTS public.rules
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule            varchar(255) not null
);

CREATE TABLE IF NOT EXISTS public.roles_have_rules
(
    user_id int REFERENCES public.users (id),
    role_id int REFERENCES public.roles (id)
);

INSERT INTO roles (id,role) VALUES (1,'Администратор'),(2,'Зарегистрированный пользователь');

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.

DROP TABLE IF EXISTS roles_have_rules CASCADE;
DROP TABLE IF EXISTS rules CASCADE;
DROP TABLE IF EXISTS users_have_roles CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;